In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv(r'C:\Users\cse\Desktop\dataset.csv')
dataset

date location  age        disease sevearity_of_the_disease  \
0    06-04-2012    India   42    heartstroke                     high   
1    07-05-2012    India   41         cancer                      low   
2    09-01-2012    India   42    heartstroke                 moderate   
3    05-11-2012    India   39         cancer                      low   
4    06-04-2012    India   43         cancer                      low   
5    07-05-2012    India   44  bone fracture                     high   
6    09-01-2012    India   50  bone fracture                 moderate   
7    05-11-2012    India   29          fever                     high   
8    09-01-2012    India   44          fever                     high   
9    09-01-2012    India   27    heartstroke                 moderate   
10   09-01-2012    India   31         cancer                     high   
11   09-01-2012    India   24  bone fracture                      low   
12   09-01-2012    India   34    heartstroke                 moderate   
13   09-01-2012    India   25         cancer                 moderate   
14   09-01-2012    India    8          fever                      low   
15   06-04-2012    India   45          fever                     high   
16   06-04-2012    India   58         cancer                 moderate   
17   06-04-2012    India   24         cancer                      low   
18   06-04-2012    India   45  bone fracture                     high   
19   06-04-2012    India   24  bone fracture                      low   
20   06-04-2012    India   41         cancer                 moderate   
21   06-04-2012    India   32          astma                      low   
22   06-04-2012    India   38         cancer                      low   
23   06-04-2012    India   46         cancer                     high   
24   06-04-2012    India   38  bone fracture                 moderate   
25   06-04-2012    India   25  bone fracture                     high   
26    8/29/2012    India   36          fever                     high   
27    5/26/2012    India   44          fever                 moderate   
28    9/22/2012    India   43          fever                     high   
29   08-09-2012    India   29    heartstroke                      low   
..          ...      ...  ...            ...                      ...   
469   3/26/2012    India    8          fever                     high   
470  08-07-2012    India   27    heartstroke                 moderate   
471  12-02-2012    India   37         cancer                      low   
472   2/27/2012    India   26  bone fracture                      low   
473   6/20/2012    India   28    heartstroke                     high   
474   9/18/2012    India   33         cancer                 moderate   
475  08-05-2012    India   46          fever                     high   
476  12/18/2012    India   31          fever                     high   
477  09-02-2012    India   40         cancer                 moderate   
478   9/28/2012    India   38         cancer                     high   
479  07-03-2012    India   29  bone fracture                      low   
480  11-11-2012    India   34  bone fracture                 moderate   
481   9/25/2012    India   23         cancer                 moderate   
482  09-01-2012    India   37          astma                      low   
483  11/18/2012    India   37         cancer                     high   
484   7/18/2012    India   61         cancer                 moderate   
485   5/16/2012    India    8  bone fracture                      low   
486  11/19/2012    India   37  bone fracture                     high   
487  12/26/2012    India   39          fever                      low   
488  11-02-2012    India   30          fever                 moderate   
489  02-05-2012    India   55          fever                      low   
490  02-05-2012    India   29    heartstroke                      low   
491  02-05-2012    India   41         cancer                     high

In [3]:
dataset.isnull().any()

date                        False
location                    False
age                         False
disease                     False
sevearity_of_the_disease    False
frequency_of_suffering      False
pulse                       False
duration_of_suffering       False
length_of_stay              False
dtype: bool

In [4]:
x = dataset.iloc[:, 2:8].values
y = dataset.iloc[:, 8].values

In [5]:
x

array([[42, 'heartstroke', 'high', 'regural', 96, 6],
       [41, 'cancer', 'low', 'irregular', 61, 2],
       [42, 'heartstroke', 'moderate', 'irregular', 64, 4],
       ...,
       [32, 'bone fracture', 'high', 'regular', 68, 6],
       [40, 'fever', 'low', 'irregular', 61, 2],
       [26, 'fever', 'moderate', 'irregular', 70, 6]], dtype=object)

In [6]:
y

array([ 3,  2,  1,  5,  2,  7,  3,  3, 10,  2,  8,  3,  6,  9,  6, 30,  7,
       10,  4, 11, 14, 12,  4,  9,  6, 12, 11,  2,  1,  5,  2, 15,  3,  3,
       10,  2,  8,  3,  6,  9,  6, 30,  7, 10,  4, 11, 14, 12,  4,  9,  6,
       12, 11,  2,  1,  5,  2, 15,  3,  3, 10,  2,  1,  5,  2, 15,  3,  3,
       10,  2,  8,  3,  6,  9,  6, 30,  7, 10,  4, 11, 14, 12,  4,  9,  6,
       12, 11,  2,  1,  5,  2, 15,  3,  3, 10,  2,  8,  3,  6,  9,  6, 30,
        7, 10,  4, 11, 14, 12,  4,  9,  6, 12, 11,  2,  1,  5,  2, 15,  3,
        3, 10,  2,  1,  5,  2, 15,  3,  3, 10,  2,  8,  3,  6,  9,  6, 30,
        7, 10,  4, 11, 14, 12,  4,  9,  6, 12, 11,  2,  1,  5,  2, 15,  3,
        3, 10,  2,  8,  3,  6,  9,  6, 30,  7, 10,  4, 11, 14, 12,  4,  9,
        6, 12, 11,  2,  1,  5,  2, 15,  3,  3, 10,  2,  1,  5,  2, 15,  3,
        3, 10,  2,  8,  3,  6,  9,  6, 30,  7, 10,  4, 11, 14, 12,  4,  9,
        6, 12, 11,  2,  1,  5,  2, 15,  3,  3, 10,  2,  8,  3,  6,  9,  6,
       30,  7, 10,  4, 11

In [7]:
from sklearn.preprocessing import LabelEncoder

#Label Encoding

labelencoder_X = LabelEncoder()
x[:, 1] = labelencoder_X.fit_transform(x[:,1])
labelencoder_X2 = LabelEncoder()
x[:, 2] = labelencoder_X2.fit_transform(x[:,2])
labelencoder_X3 = LabelEncoder()
x[:, 3] = labelencoder_X3.fit_transform(x[:,3])


In [8]:
x

array([[42, 4, 0, 2, 96, 6],
       [41, 2, 1, 0, 61, 2],
       [42, 4, 2, 0, 64, 4],
       ...,
       [32, 1, 0, 1, 68, 6],
       [40, 3, 1, 0, 61, 2],
       [26, 3, 2, 0, 70, 6]], dtype=object)

In [9]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [1])
x = onehotencoder.fit_transform(x).toarray()
x=x[:,1:]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [10]:
x.shape


(499, 9)

In [11]:
onehotencoder = OneHotEncoder(categorical_features = [6])
x = onehotencoder.fit_transform(x).toarray()
x=x[:,1:]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [12]:
x

array([[ 0.,  1.,  0., ...,  0., 96.,  6.],
       [ 0.,  0.,  0., ...,  1., 61.,  2.],
       [ 0.,  0.,  0., ...,  2., 64.,  4.],
       ...,
       [ 1.,  0.,  1., ...,  0., 68.,  6.],
       [ 0.,  0.,  0., ...,  1., 61.,  2.],
       [ 0.,  0.,  0., ...,  2., 70.,  6.]])

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [14]:
x_train

array([[ 0.,  0.,  1., ...,  1., 64.,  2.],
       [ 1.,  0.,  1., ...,  1., 77.,  2.],
       [ 1.,  0.,  1., ...,  1., 88.,  2.],
       ...,
       [ 0.,  0.,  0., ...,  0., 71.,  6.],
       [ 0.,  0.,  1., ...,  1., 73.,  2.],
       [ 1.,  0.,  1., ...,  1., 95.,  2.]])

In [15]:
y_train

array([12,  3,  3, 11,  3,  6,  2,  2,  3,  2, 15,  3, 10, 10,  2, 30,  3,
       10,  2, 10, 10,  9,  6,  5,  8,  3,  3,  4,  5,  9,  1,  9,  2,  5,
       11,  3,  8,  2,  2,  3,  6, 11,  6, 11, 15,  2, 10,  5,  2,  7, 12,
       12, 30,  8,  1,  4, 10, 14,  9,  6,  3, 11,  2, 11, 12, 12,  1,  2,
        7,  9,  3,  6,  2,  1,  9, 11,  4, 12, 15,  2,  2,  4, 14,  3,  5,
        7, 15, 10, 11,  5,  3,  5,  3, 15,  3,  3,  3,  3,  4,  4, 12,  6,
        2, 15, 12,  6,  6, 10,  3, 10,  6, 14, 30,  3,  1, 14, 10, 11, 10,
        4,  2,  1,  3, 10, 12,  2,  2, 15,  2,  4,  2, 10, 14, 11,  2,  3,
       30,  7,  8, 11,  2,  3,  6,  3, 11,  3, 11, 11,  9,  3,  1,  7, 10,
        4,  3, 12,  2, 11,  2,  6,  9,  2,  1,  5,  3,  9, 12,  3,  2,  6,
        4,  8, 12, 10,  4,  3,  4,  7,  4,  9,  2, 11,  2, 10,  6,  1,  4,
        3,  6,  8, 10,  2, 12, 14,  5,  3,  6,  3,  9, 11,  6,  6,  9, 14,
       12,  3,  4, 30,  9,  6,  2,  6,  5,  3,  7,  9,  9,  6, 11, 15, 11,
        2,  7,  6,  6,  3

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
mlr=LinearRegression()

In [18]:
mlr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [19]:
y_pred = mlr.predict(x_test)

In [20]:
x_test

array([[  1.,   0.,   0.,   1.,   0.,   0.,  44.,   0.,  67.,   6.],
       [  1.,   0.,   0.,   1.,   0.,   0.,  28.,   2.,  96.,   4.],
       [  0.,   0.,   0.,   1.,   0.,   0.,  42.,   2.,  85.,   4.],
       [  0.,   0.,   0.,   0.,   1.,   0.,  47.,   2.,  88.,   4.],
       [  1.,   0.,   0.,   1.,   0.,   0.,  33.,   2.,  59.,   4.],
       [  0.,   0.,   0.,   0.,   1.,   0.,  45.,   0.,  68.,   6.],
       [  1.,   0.,   0.,   1.,   0.,   0.,  49.,   0.,  80.,   6.],
       [  0.,   0.,   0.,   0.,   1.,   0.,  30.,   2.,  77.,   4.],
       [  0.,   0.,   0.,   0.,   1.,   0.,  33.,   0.,  75.,   6.],
       [  1.,   0.,   0.,   0.,   0.,   0.,  37.,   2.,  96.,   4.],
       [  1.,   0.,   0.,   0.,   1.,   0.,  39.,   0.,  78.,   6.],
       [  1.,   0.,   0.,   1.,   0.,   0.,  36.,   2.,  67.,   4.],
       [  1.,   0.,   0.,   0.,   1.,   0.,  33.,   0.,  56.,   6.],
       [  1.,   0.,   1.,   0.,   0.,   0.,  34.,   1.,  86.,   2.],
       [  1.,   0.,   0.,   1.,   

In [21]:
y_pred

array([7.35000845, 7.96105362, 6.79866157, 6.27949315, 6.88903537,
       6.69625948, 7.4178671 , 6.80565202, 7.40426469, 6.72719614,
       7.47023904, 6.93431006, 7.24290443, 8.07428472, 8.26372548,
       8.82938012, 6.90878657, 7.22960107, 7.89725616, 7.33384905,
       8.1324821 , 6.73693902, 7.02099675, 8.19040223, 7.34687042,
       8.65331271, 6.89326442, 7.15253063, 6.86538347, 7.99219194,
       5.96974695, 7.32417968, 8.58278421, 6.48248156, 7.18818907,
       7.05318134, 8.29458993, 7.69911529, 7.64146091, 7.64413983,
       6.89006531, 7.62717191, 6.9234873 , 8.14739437, 6.89085993,
       6.93972763, 7.63213328, 8.70259368, 8.10744795, 7.62537997,
       6.5284108 , 7.67118863, 6.96390743, 7.88210442, 7.79218974,
       7.35326663, 7.03431523, 7.71667691, 7.34561179, 6.93409647,
       7.34247376, 6.15212725, 7.2432936 , 6.74249533, 7.1460977 ,
       7.11282767, 8.08091799, 7.19876647, 7.4876161 , 8.3829407 ,
       6.7343362 , 7.25513726, 7.73810057, 7.14660811, 8.38342

In [22]:
y_test

array([ 2,  9,  7,  9,  2, 30, 30,  3,  9,  3,  5,  2,  3,  4, 12,  2, 14,
        2, 10,  3, 12,  2, 10,  4, 11,  7, 12, 15,  8,  2, 11,  3,  2,  3,
       15, 15,  8,  6, 12,  3, 12, 14, 30, 30,  7,  2,  3,  6,  2,  7,  2,
        6, 30,  6,  6,  6, 11,  2,  4,  2,  4,  2, 12,  5, 10,  7,  8,  7,
        2, 30,  4, 15,  6, 15,  5, 10,  9,  6, 10,  1,  3,  5,  2,  9,  1,
       12,  9,  3, 14,  1,  6,  6, 10, 14,  3, 14,  2,  4, 10,  1],
      dtype=int64)

In [23]:
mlr.intercept_

7.242818944640025

In [24]:
x_train.shape

(399, 10)

In [25]:
mlr.coef_

array([ 0.27179295, -5.08813056,  0.79545324,  0.82254065,  0.46348896,
        1.07992336, -0.04570187, -0.47460615,  0.02279754, -0.08394947])

In [26]:
from sklearn.metrics import r2_score

In [27]:
r2_score(y_test,y_pred)

-0.01767735887582167

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets